Add .editorconfig
Assorted-Development/winforms-themes pull request #21
Opened 2023-08-13 08:30 UTC by Nockiro

## About this PR
This PR aims to add analyzer/code style rules for keeping our code style consistent in the future.

## ToDos
- [ ] Discuss about the new ruleset
- [ ] Fix warnings that arise with the new ruleset and really should be handled
- [ ] Disable rules that are not useful for us

## Checklist
(Please strikethrough all not applicable points instead of removing them)

- [ ] ~I have added a suitable test~
- [ ] I have updated the documentation in the readme

2023-08-13 09:26 UTC, wolframhaussig requested changes

2023-08-13 09:26 UTC, wolframhaussig commented on WinFormsThemes/.editorconfig
> +insert_final_newline = unset
We do not use Cobol (and hopefully never will). Please remove this block

2023-08-13 09:26 UTC, wolframhaussig commented on WinFormsThemes/TestProject/AbstractThemeTest.cs
> +            IThemeRegistry registry = ThemeRegistryHolder.GetBuilder()
I understand prefering `ThemePlugin plugin = new();` over `var plugin = new ThemePlugin();`, but why is it not allowed to have `var` here where we want to capture the result of the builder?

2023-08-13 09:26 UTC, wolframhaussig commented on WinFormsThemes/TestProject/AbstractTestClass.cs
>  namespace TestProject
UnitTests fail. Please check and fix: https://github.com/Assorted-Development/winforms-themes/pull/21/checks?check_run_id=15851393607

2023-10-21 10:10 UTC, Nockiro commented on WinFormsThemes/TestProject/AbstractThemeTest.cs
> +            IThemeRegistry registry = ThemeRegistryHolder.GetBuilder()
In my opinion, using `var` leads to confusion if it's not absolutely clear what the return type ist (e.g. string).  
It might be a bit shorter than using the type directly, but you also have to look for what the method returns every time you want to change something in that code - except for when you're extremely familiar with it, but we should (also: IMO) not assume that anywhere.

2023-10-22 08:27 UTC, Nockiro commented on WinFormsThemes/TestProject/AbstractTestClass.cs
>  namespace TestProject
Should be fixed with the latest commit - thanks!

2023-10-22 17:00 UTC, Nockiro commented
@wolframhaussig Since there are now only a few warnings left, I'd like your opinion on the following ones:

- [CA2254](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca2254), e.g. for `_logger.LogError($"ThemePlugin for {t.Name} already added");`
- [CA1024](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1024) (Use properties where appropriate) for public static IThemeRegistryBuilder GetBuilder
- [CA2227](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca2227), e.g. "Change 'ThemePlugins' to be read-only by removing the property setter

I would like to simply disable CA1024 - I think we're old enough to know where we should or shouldn't use properties.
CA1024 is a bit interesting, I think it would make coding a bit more complicated but it'd make it easier in the future to react to changes inside the list.  
As for CA2254.. I wouldn't mind deactivating it as well as I wouldn't mind keeping it on or setting it to "hint".

What do you think?

2023-10-22 20:04 UTC, wolframhaussig commented on WinFormsThemes/WinFormsThemes/ThemeConfig/ThemeRegistryBuilder.cs
> +        public void Dispose()
I have a few issues here:
1. When calling the method the easy way, the dispose method will not be called: `ThemeRegistryHolder.GetBuilder().SetLoggerFactory(LoggerFactory).Build()`
2. Running the code with a `using`-directive makes it more verbose and less readable in my mind
3. The most important topic: The following code fails, so the logging would break as soon as the Theme library was initialized:
```csharp
using(var builder = ThemeRegistryHolder.GetBuilder())
{
    builder.SetLoggerFactory(LoggerFactory).Build();
}
Logger<ThemeRegistryBuilderTest> l = new Logger<ThemeRegistryBuilderTest>(LoggerFactory);
l.LogInformation("Logging still working after Builder is done");
```
The error is obviously:
> Test method TestProject.ThemeRegistryBuilderTest.BuilderShouldNotCloseLoggerFactory threw exception: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.

2023-10-22 20:15 UTC, wolframhaussig commented
> @wolframhaussig Since there are now only a few warnings left, I'd like your opinion on the following ones:
> 
>     * [CA2254](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca2254), e.g. for `_logger.LogError($"ThemePlugin for {t.Name} already added");`
> 
>     * [CA1024](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1024) (Use properties where appropriate) for public static IThemeRegistryBuilder GetBuilder
> 
>     * [CA2227](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca2227), e.g. "Change 'ThemePlugins' to be read-only by removing the property setter
> 
> 
> I would like to simply disable CA1024 - I think we're old enough to know where we should or shouldn't use properties. CA1024 is a bit interesting, I think it would make coding a bit more complicated but it'd make it easier in the future to react to changes inside the list. As for CA2254.. I wouldn't mind deactivating it as well as I wouldn't mind keeping it on or setting it to "hint".
> 
> What do you think?

So, here are my thoughts on this:
- `CA2254`: I am torn here - on one side it is more performant when the string building only takes place when the log level is really enabled and as this is a trace level this is not very often the case. on the other hand, it is more easily readable when directly embedded in the string. I wouldn't mind either way.
- `CA2227`: They are right, we should only allow setting it once. I must confess, I did this instead of adding a constructor to each subclass of `AbstractTheme` but this might cause the plugins to change between runs and I would rather have the whole ThemeRegistry rebuilt when this is required.
- `CA1024`: is not shown in my list, where did you get that?
- `CA1716`: This was not in your list, but I find it interesting: `Identifiers should not match keywords`. This is related to `IThemeRegistry.Get` because `Get` is a reservered keyword and `VB.NET` is case insensitive so there might be errors. Should we rename `Get` then?

2023-10-25 09:15 UTC, wolframhaussig approved these changes

2023-10-25 11:09 UTC, merged